AllCops:
   Exclude:
     - 'app/admin/sound_cloud_tracks.rb'
     - 'app/lib/**/*'
     - 'app/lib/**/*'
     - 'db/**/*'
     - 'config/**/*'
     - 'features/**/*'
     - 'script/**/*'
     - 'bin/{rails,rake}'
     - 'node_modules/*'
     - 'node_modules/*/*/*/*/*'
     - 'bin/*'
     - 'lib/**/*'
     - 'log/**/*'
     - 'path/**/*'
     - 'public/**/*'
     - 'spec/**/*'
     - 'tmp/**/*'
     - 'Dockerfile*'
     - 'test/**/*'
     - 'vendor/**/*'
     - 'Gemfile*'
     - 'app/helpers/csv_books_helper.rb'
     - 'app/jobs/application_job.rb'
     - 'app/mailers/application_mailer.rb'
     - !ruby/regexp /old_and_unused\.rb$/

Lint/UnneededCopDisableDirective:
  Enabled: false

Style/Encoding:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 50

Metrics/AbcSize:
  Max: 25

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/HashEachMethods:
    Enabled: true

Style/HashTransformKeys:
    Enabled: true

Style/HashTransformValues:
    Enabled: true
